// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentGradeApi.Data;

#nullable disable

namespace StudentGradeApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129162321_AddCourseYears")]
    partial class AddCourseYears
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentGradeApi.Models.Course", b =>
                {
                    b.Property<string>("CourseName")
                        .HasColumnType("text")
                        .HasColumnName("course_name");

                    b.Property<int>("Credits")
                        .HasColumnType("integer")
                        .HasColumnName("credits");

                    b.Property<int>("YearNum")
                        .HasColumnType("integer")
                        .HasColumnName("year_num");

                    b.HasKey("CourseName");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("StudentGradeApi.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("enrollment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnrollmentId"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_name");

                    b.Property<decimal>("Grade")
                        .HasColumnType("numeric")
                        .HasColumnName("grade");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<string>("TermType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("term_type");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseName");

                    b.HasIndex("StudentId");

                    b.ToTable("enrollments");
                });

            modelBuilder.Entity("StudentGradeApi.Models.Student", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("StudentId");

                    b.ToTable("students");
                });

            modelBuilder.Entity("StudentGradeApi.Models.StudentCgpa", b =>
                {
                    b.Property<decimal>("CalculatedCgpa")
                        .HasColumnType("numeric")
                        .HasColumnName("calculated_cgpa");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.ToTable("student_cgpa_view");

                    b.ToView("student_cgpa_view", (string)null);
                });

            modelBuilder.Entity("StudentGradeApi.Models.Enrollment", b =>
                {
                    b.HasOne("StudentGradeApi.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentGradeApi.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentGradeApi.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
